version: '3.7'

services:
  web:
    build: .
    container_name: ischedule-backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/ischedule
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: ischedule-database
    image: onjin/alpine-postgres:9.6
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ischedule
